apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-hello
spec:
  template:
    spec:
      containers:
        - name: quarkus-hello
          image: >-
            image-registry.openshift-image-registry.svc:5000/devops-practice/quarkus-hello:db879e59069b977284a51a28aa2451ed66839b94