apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-hello
spec:
  template:
    spec:
      containers:
        - name: quay.io/tadianto/quarkus-hello:c2673f546236f778fb9f79ada9b1e29b5247c9bd