apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-hello
spec:
  template:
    spec:
      containers:
        - name: quarkus-hello
          image: quay.io/tadianto/quarkus-hello:b90bf82239791096f117353716f1ac2e130330ee
