kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-edit-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: quarkus-hello-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit