kind: Secret
apiVersion: v1
metadata:
  name: git-credential-secret
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://troy-adianto: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@github.com

---

kind: Secret
apiVersion: v1
metadata:
  name: quay-registry-credential
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoidGFkaWFudG8rb2NwcGlwZWxpbmUiLCJwYXNzd29yZCI6IkVMRUJXRlg3TDlLTTBVMVNONFFCQ0xTM0JSRUZUVVMyNTBZVE1JUTVNVzFVTEc0NVo4SlYyUkU4VDFWSEhJTEwiLCJhdXRoIjoiZEdGa2FXRnVkRzhyYjJOd2NHbHdaV3hwYm1VNlJVeEZRbGRHV0RkTU9VdE5NRlV4VTA0MFVVSkRURk16UWxKRlJsUlZVekkxTUZsVVRVbFJOVTFYTVZWTVJ6UTFXamhLVmpKU1JUaFVNVlpJU0VsTVRBPT0iLCJlbWFpbCI6IiJ9fX0=
type: kubernetes.io/dockerconfigjson

---

kind: Secret
apiVersion: v1
metadata:
  name: acs-pipeline-secret
data:
  rox_api_token: <token>
  rox_central_endpoint: <endpoint>
type: Opaque