kind: Secret
apiVersion: v1
metadata:
  name: git-credential-secret
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://<user>:<password>@github.com

---

kind: Secret
apiVersion: v1
metadata:
  name: quay-registry-credential
data:
  .dockerconfigjson: >-
    {"auths":{"quay.io":{"username":"tadianto+ocppipeline","password":"ELEBWFX7L9KM0U1SN4QBCLS3BREFTUS250YTMIQ5MW1ULG45Z8JV2RE8T1VHHILL","auth":"dGFkaWFudG8rb2NwcGlwZWxpbmU6RUxFQldGWDdMOUtNMFUxU040UUJDTFMzQlJFRlRVUzI1MFlUTUlRNU1XMVVMRzQ1WjhKVjJSRThUMVZISElMTA==","email":""}}}
type: kubernetes.io/dockerconfigjson

---

kind: Secret
apiVersion: v1
metadata:
  name: acs-pipeline-secret
data:
  rox_api_token: <token>
  rox_central_endpoint: <endpoint>
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: pipeline-generic-webhook-secret
data:
  WebHookSecretKey: <webhook secret>
type: Opaque